### ISSUE TITLE
withFassets API

### ISSUE THREAD

**Issue by sylvainlg** [KevinAst/feature-u#24]
The https://github.com/KevinAst/feature-redux/issues/15#issuecomment-568740110 comment remind me something i saw few days ago.

I wonder if `withFassets` API may be implemented as classics HOCs. If we take a look at `connect` (from `react-redux`), the usage is : `connect(mapStateToProps, mapDispatchToProps)(Component)`.

The current `withFassets` implementation is :
```js
withFassets(mapFassetsToProps, Component)
could be :
withFassets(mapFassetsToProps)(Component)
```

What do you think about that ?

**Comment by KevinAst** [comment]
Actually, `withFassets()` already supports this "classic" technique.  There are two different ways to invoke it _(please refer to the [`withFassets()`](https://feature-u.js.org/cur/api.html#withFassets) API docs)_.

1. By directly passing the `component` parameter, the HoC will be returned _(internally invoking the HoF)_.  This is the most common use case.

2. By omitting the `component` parameter, the HoF will be returned.  This is useful to facilitate "functional composition" _(in functional programming)_.  In this case it is the client's responsibility to invoke the HoF _(either directly or indirectly)_ in order to expose the HoC.

**Please Note** that `withFassets()` uses named parameters, which I much prefer for this particular API.  This is only real difference to the "classic" API.
