### ISSUE TITLE
Experiencing freeze on the documentation search

### ISSUE THREAD

**Issue by ScreamZ** [KevinAst/feature-u#35]
Also, do you experience UI freezes when using the search on the documentation website? I have some.

I'm using Microsoft Edge (chromium based) but I had also with safari

**Comment by KevinAst** [comment]
**feature-u** docs utilize [GitBook](https://www.gitbook.com/).  I have **not** used the search feature extensively, but I have noticed it is a bit quirky ... and yes it does lock the browser up on occasion :-(

Unfortunately, researching this issue is **not** high on my priority list, as it ultimately is a GitBook issue ... sorry :-(

FYI: If interested, the following article covers how the docs are generated/maintained: [Integrating GitBook with JSDoc to Document Your Open Source Project](https://medium.com/@kevinast/integrate-gitbook-jsdoc-974be8df6fb3)
